name: release-automation

on: [push]

jobs:
  get-target-names:
    runs-on: ubuntu-22.04
    outputs:
      target-names: ${{ steps.targets-listing.outputs.TARGET_NAMES }}
    steps:
      - uses: actions/checkout@v2
      - id: targets-listing
        run: echo "TARGET_NAMES=$(tools/shell/build.sh --targets | jq -R . | jq -s . | jq -c)" >> $GITHUB_OUTPUT

  publish-packages:
    runs-on: ubuntu-22.04
    needs:
      - get-target-names
    strategy:
      matrix:
        targets: ${{ fromJSON(needs.get-target-names.outputs.target-names) }}

    steps:
      - uses: actions/checkout@v2
      - name: package precompiled ${{ matrix.targets }}
        run: tools/shell/package.sh precompiled ${{ matrix.targets }}
      - name: upload to GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth status
